### ISSUE TITLE
Show number of cards in the draw pile

### ISSUE THREAD

**Issue by jak103** [jak103/uno#151]

**Comment by hhenrichsen** [comment]
Has there been any progress on this yet @brent-buffenbarger? Is there anywhere I can help?

**Comment by brent-buffenbarger** [comment]
@hhenrichsen I haven’t had time to look at this issue yet, but I am planning on working on it today. If I run into any issues I will reach out to you or the class for some help. Thanks!

**Comment by jak103** [comment]
Merged.
