### ISSUE TITLE
Add chat feature

### ISSUE THREAD

**Issue by jak103** [jak103/uno#154]
Let's get a chat feature built in so we can trash talk each other

**Comment by mcmullinboy15** [comment]
Created the Branch `chat` for this issue

**Comment by mcmullinboy15** [comment]
![image](https://user-images.githubusercontent.com/48926044/89112949-ca3c8b80-d427-11ea-926d-2e8c890e57db.png)

**Comment by mcmullinboy15** [comment]
Any Objections to how this is turning out? I can make it just on the side, like the chat it Webex, if people want it that way, because this does cover the cards up. I had a thought we could nudge the cards over when this is displayed but whatever.  This is only frontend so far.

**Comment by logan-hendricks** [comment]
I think that looks great so far.

**Comment by mcmullinboy15** [comment]
Thanks!

**Comment by jak103** [comment]
@mcmullinboy15 Move this to the In Progress state on the project so that others know it is being working and don't duplicate the work.

**Comment by mcmullinboy15** [comment]
Ok! I didn't know that was a thing haha. I just finished it. I think it just needs to be tested for bugs and also on a semi-production env because I was able to test a little on responses but though some dumb hacks haha. So there was never two players communicating
