### ISSUE TITLE
Create vue-switch for vue-navigation-drawer

### ISSUE THREAD

**Issue by logan-hendricks** [jak103/uno#163]
We recently implemented a `vue-navigation-drawer` to show all of the players.

It currently is set to expand on hover. Which allows players to have it collapse when it's not being viewed.

However, Some players may want to have it always open.

We can build in a vue-switch - See documentation [HERE](https://vuetifyjs.com/en/components/selection-controls/#switches-boolean) to toggle it always to be open

You can also see an example of how to integrate the switch [HERE](https://vuetifyjs.com/en/components/navigation-drawers/#playground)

**Comment by bradytrappett** [comment]
Finished and merged

**Comment by jak103** [comment]
I'm not sure this is actually in there, reopening until the PR is merged.
