### ISSUE TITLE
Create DB interface

### ISSUE THREAD

**Issue by jak103** [jak103/uno#17]
![databaseInterface](https://user-images.githubusercontent.com/964779/86419519-a5ba8b80-bc90-11ea-9723-eab219bff949.PNG)

The interface needs to be able to connect to a local docker container mongoDB, the Google Cloud Firestore, optionally a Mock DB.

**Comment by hhenrichsen** [comment]
I think the way we want to do this, we set it up so that we have some general interface, then move `uno.go` to be the implementation of the mock database. I think it should look something like this:

```go
type unoDB interface {
	// Check if a game with the given ID exists in the database.
	hasGame(game string) bool
	// Returns if the game ID is valid and started.
	isGameRunning(game string, username string) bool
	// Marks a game as started.
	startGame(game string)
	// Creates a game with the given ID. Perhaps this should instead just return an id?
	createGame(id string)
	// Joins a player to a game.
	joinGame(game string, username string)
	// Plays a card from a player's hand.
	playCard(game string, username string, card Card)
	// Gets a player's hand.
	getHand(game string, username string) []Card
	// Gets the next card off the top of the deck.
	nextCard(game string) Card
	// Pops the next card off the top of the deck.
	drawCard(game string) Card
	// Checks for any winners, returning the winner's name if they exist.
	checkForWinner() string
}
```

**Comment by Ryan-Johnson-1315** [comment]
Hey sorry. I haven't been very good at getting back. If you want to go to my repo and look at the unit_testing branch. I have some stuff started.

What I was thinking is that in the web.go file interacts with the database and the uno logic. I was trying to make it so the uno.go file and the db.go file never make any calls to each other.

Let me know what you think. I switched to a mac and am trying to get docker to work with it and having some troubles. 
https://github.com/Ryan-Johnson-1315/usu-uno/tree/unit_testing

**Comment by hhenrichsen** [comment]
I'm not sure I understand why we'd separate the uno logic and the database. Separating those and not making calls from uno to the database seems like it'd just make things more complex. I think we should define what the database should be able to do (like the interface above), and then write separate implementations and let uno call into it as needed. 

To rephrase -- what was your intent in making it so the `uno.go` file and the `db.go` file never make any calls to each other? What would that accomplish?

**Comment by Ryan-Johnson-1315** [comment]
It would make it easier to test. Rather than worrying about the database part of the uno logic, the uno logic is by itself. Then when you test, the only thing you have to worry about testing is the uno logic, then the database to make sure it is working as expected.

This solves the problem with what we had when we started testing the backend. We had to make sure the requests were working just to make sure the uno logic was working. Making more work than needed.

**Comment by hhenrichsen** [comment]
I think that was the whole point of the mock database -- to test the database without testing a real database, and to know that it responds as expected. We just tell our implementation to use the mock database, and everything works as expected. I think it adds more complexity than it's worth to set up a super hard boundary like that, especially if we couple it loosely with an interface.

**Comment by Ryan-Johnson-1315** [comment]
Ok...how would you do it. It seems like you want the database different from the uno. Then you can test them separately

**Comment by hhenrichsen** [comment]
The way I'd do it is to create an interface like above that defines what the database is expected to be able to do, then to create a mock copy that we use for testing. If the testing copy is working inside of its defined functionality, we shouldn't have to worry about the others breaking if implemented properly. The database provides data, `uno` validates it, and then `routeHandlers` sends/receives it.

**Comment by Ryan-Johnson-1315** [comment]
So in order to test the database, you also have to test the uno logic at the same time...?

**Comment by hhenrichsen** [comment]
No. You test the database on its own, and use the mock database (which you can test separately if needed) to test the uno functions.

**Comment by hhenrichsen** [comment]
I guess the thing I don't see is how splitting them up would help us keep things clean. What would playing a card look like in your vision, and what would a test look like that? I think there's a dependency on the code working in both of them either way, but I'm happy to do it your way -- I'd learn something either way, I just need to see how it'd go, and what the differences would be.

**Comment by Ryan-Johnson-1315** [comment]
Hey sorry. I've been on vacation the last week. We should decide on a game plan and just go with it. It doesn't matter to me. We can do it the way you were describing..you might just need to walk me through it while we are getting started. What do you think?

**Comment by Ryan-Johnson-1315** [comment]
This is what I started with. Not sure if we want to keep it or not
https://github.com/Ryan-Johnson-1315/usu-uno/blob/unit_testing/server/database.go

**Comment by logan-hendricks** [comment]
Resolved and implemented
