### ISSUE TITLE
Unit tests for uno.goToNextPlayer

### ISSUE THREAD

**Issue by logan-hendricks** [jak103/uno#182]
As a class, we should have written the unit test for uno.goToNextPlayer when rounding out the application... however, we stampeding features, and didn't have time.

This particular method does not have any unit tests created for it.

Write a unit test that sets up the data in the database required for going to the next player, and then write the unit test for goToNextPlayer

**Comment by Jaredcscott** [comment]
I will have this done before class on Tuesday.
