### ISSUE TITLE
Bug when Non-number Card is first in the game

### ISSUE THREAD

**Issue by logan-hendricks** [jak103/uno#192]
When a wild or W4 is the very first card in the discard pile. it's impossible to play any cards because a color has not been decided.  We should prevent Wild or W4 being the first card on the discard pile. and always ensure it's a colored card.

EDIT - The bug here is actually that any non-number card is the first one.  So like Skip, Reverse, Draw 2 are also impacting play when they are the first card on the top of the discard pile.

**Comment by mcmullinboy15** [comment]
I was just about to make an issue for this. NOTE: No non-number Cards should ever be the first Card
