### ISSUE TITLE
Unit tests should use mock db

### ISSUE THREAD

**Issue by marwtki** [jak103/uno#224]
Running unit tests causes games with names "Game 1" and "testGame" to be added to the list of games on the homepage. Running tests should not add games into the actual database.

**Comment by Jaredcscott** [comment]
Looks like this is the problem 
```
database, err := db.GetDb()
	assert.Nil(t, err, "could not find database")
	// create a new game with one player
	game, _, err := createNewGame("testGame", "testPlayer")
```
What is the call for the mock db?

**Comment by Jaredcscott** [comment]
Never mind I think I found it.
