### ISSUE TITLE
Remove short scroll on Game.vue

### ISSUE THREAD

**Issue by jak103** [jak103/uno#285]
There is about a 65 pixel scroll that is always present. Let's get that eliminated so the scroll bar doesn't show up

**Comment by logan-hendricks** [comment]
On which side is the short scroll present?

**Comment by logan-hendricks** [comment]
I ask because I just fixed a number of small scrolling issues. and I thought I addressed all of them.

**Comment by jak103** [comment]
I fixed this last night.
