### ISSUE TITLE
Create game lobby

### ISSUE THREAD

**Issue by jak103** [jak103/uno#82]
Show all running games on server and allow others to join a game.

Maybe even password protect games to prevent random players from joining.

Join by ID, to allow private games.

**Comment by chaosreader** [comment]
Its easy to un - assign people

**Comment by hhenrichsen** [comment]
I think this one depends a bit on the database split (#17) -- If we get a game 'object' back from the database and it's methods, the rest should just be creating proper routes and implementing the frontend.

**Comment by chaosreader** [comment]
We are going to create text channel wit the same name on the discord to keep the communication lines open.

**Comment by chaosreader** [comment]
Please comment on the discord text channel on Friday by 7 to update team and share progress
