### ISSUE TITLE
Show number of cards in all players hands

### ISSUE THREAD

**Issue by jak103** [jak103/uno#88]
Otherwise we don't know when to call uno

**Comment by ellisza** [comment]
https://discord.gg/rCKwuz

**Comment by ellisza** [comment]
Documenting for my own benefit.  I will create a function to display another box, below the player names that will grab the number of cards from the database.

**Comment by Aaron-Fine** [comment]
I will add a new endpoint on the server to return card counts for each player.

Any preferences on a name for the endpoint? Any requests for the data structure it is going to return?

Initial proposal:
`/cardCount?gameID=####` => `{ "handOverview" : [ {"name": "player 1", "numCards" : 3 }, {"name": "player 2", "numCards" : 1 } ], "error" : "" }`

**Comment by Aaron-Fine** [comment]
@SEM9799 created a branch for us to use: show-num-cards
