### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by jak103** [jak103/uno#98]
We are low in test coverage. Let's get this up above 90%

![image](https://user-images.githubusercontent.com/964779/88180248-53fb8600-cbea-11ea-8790-ed08b5cd1f08.png)

**Comment by nathanj9** [comment]
I missed the last half of class and waiting for the recording to see how the class decided these things but Ill try and get the route Handlers to 90% or more. and we will see if I should make an official pull request or if we are going to just push to master or something else.

**Comment by Jaredcscott** [comment]
I will work on the deckUtils.go file, from what I can see the functions printCards and printCard as well as the type UnoCard are the untested portions.  Working with Nathan, we feel that I should write unit tests for the getDeckConfig and shuffleCards functions too in order to test more exhaustively.

**Comment by jak103** [comment]
Pull request please.

**Comment by nathanj9** [comment]
Sent pull request but saw it failing on the workflows with my TestCheckID, maybe we can just add the routehandlers_test only then

**Comment by BrettSpackman** [comment]
Do we have a discord channel setup yet? I am not seeing one

**Comment by Jaredcscott** [comment]
I do not think so.

**Comment by BrettSpackman** [comment]
Ok I just created it. #unit-testing

**Comment by Jaredcscott** [comment]
I'll create one called increase-test-coverage

**Comment by Jaredcscott** [comment]
Nevermind, someone created another one I'll delete mine.

**Comment by Jaredcscott** [comment]
So the path to the package model is declared as github.com/jak103/uno, but the real location is github.com/jak103/uno/server. This is also true for the package db. 

go: finding module for package github.com/jak103/uno/server/model
go: downloading github.com/jak103/uno/server v0.0.0-20200724022813-5b52af632fd9
go: found github.com/jak103/uno/server/model in github.com/jak103/uno/server v0.0.0-20200724022813-5b52af632fd9
go: github.com/jak103/usu-uno tested by
        github.com/jak103/usu-uno.test imports
        github.com/jak103/uno/server/model: github.com/jak103/uno/server@v0.0.0-20200724022813-5b52af632fd9: parsing go.mod:
        module declares its path as: github.com/jak103/uno  <----------------------------------------- Can we fix this???
                but was required as: github.com/jak103/uno/server

**Comment by logan-hendricks** [comment]
@Jaredcscott @BrettSpackman @nathanj9 Can we merge in whatever you guys have written at this point and close out this ticket? I recently just wrote out a bunch of smaller issues to ensure people can have divided work.  I'd love to have this in ASAP so your work isn't written by others.

I can close out the duplicate issues if you already have unit tests written.
